"""Provision least-privilege PostgreSQL login roles for application workloads."""

from __future__ import annotations

import argparse
import os
import secrets
from pathlib import Path
from urllib.parse import quote, urlparse, urlunparse

import psycopg
from psycopg import sql

from app.config import settings

ROLE_PRIVILEGES = {
    "app_reader": "SELECT",
    "app_writer": "SELECT, INSERT, UPDATE, DELETE",
    "etl_writer": "SELECT, INSERT, UPDATE, DELETE",
}


def connection_url_for_role(admin_url: str, role: str, password: str) -> str:
    """Replace only credentials while preserving endpoint, database, and SSL query."""
    parsed = urlparse(admin_url)
    host = parsed.hostname
    if not host:
        raise ValueError("DATABASE_URL has no hostname")
    port = f":{parsed.port}" if parsed.port else ""
    netloc = f"{quote(role, safe='')}:{quote(password, safe='')}@{host}{port}"
    return urlunparse(parsed._replace(netloc=netloc))


def _role_exists(connection: psycopg.Connection, role: str) -> bool:
    row = connection.execute(
        "SELECT EXISTS(SELECT 1 FROM pg_roles WHERE rolname = %s)", (role,)
    ).fetchone()
    return bool(row and row[0])


def _create_login_role(
    connection: psycopg.Connection,
    role: str,
    password: str,
) -> None:
    connection.execute(
        sql.SQL("CREATE ROLE {} LOGIN PASSWORD {}").format(
            sql.Identifier(role), sql.Literal(password)
        )
    )
    connection.execute(
        sql.SQL("ALTER ROLE {} SET statement_timeout = '30s'").format(
            sql.Identifier(role)
        )
    )


def _grant_privileges(
    connection: psycopg.Connection,
    owner: str,
    database: str,
    role: str,
    privileges: str,
) -> None:
    role_id = sql.Identifier(role)
    connection.execute(
        sql.SQL("GRANT CONNECT ON DATABASE {} TO {}").format(
            sql.Identifier(database), role_id
        )
    )
    connection.execute(
        sql.SQL("GRANT USAGE ON SCHEMA public TO {}").format(role_id)
    )
    connection.execute(
        sql.SQL("GRANT {} ON ALL TABLES IN SCHEMA public TO {}").format(
            sql.SQL(privileges), role_id
        )
    )
    connection.execute(
        sql.SQL("ALTER DEFAULT PRIVILEGES FOR ROLE {} IN SCHEMA public "
                "GRANT {} ON TABLES TO {}").format(
            sql.Identifier(owner), sql.SQL(privileges), role_id
        )
    )
    if role != "app_reader":
        connection.execute(
            sql.SQL("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {}").format(
                role_id
            )
        )
        connection.execute(
            sql.SQL("ALTER DEFAULT PRIVILEGES FOR ROLE {} IN SCHEMA public "
                    "GRANT USAGE, SELECT ON SEQUENCES TO {}").format(
                sql.Identifier(owner), role_id
            )
        )
    else:
        connection.execute(
            sql.SQL("ALTER ROLE {} SET default_transaction_read_only = on").format(
                role_id
            )
        )


def provision_roles(admin_url: str) -> dict[str, str]:
    parsed = urlparse(admin_url)
    if not parsed.hostname or "neon.tech" not in parsed.hostname:
        raise RuntimeError("Role provisioning is restricted to a confirmed Neon endpoint")

    passwords = {role: secrets.token_urlsafe(32) for role in ROLE_PRIVILEGES}
    with psycopg.connect(admin_url) as connection:
        identity = connection.execute(
            "SELECT current_user, current_database()"
        ).fetchone()
        if identity is None:
            raise RuntimeError("Could not identify PostgreSQL owner and database")
        owner, database = identity
        existing = [role for role in ROLE_PRIVILEGES if _role_exists(connection, role)]
        if existing:
            raise RuntimeError(
                "Refusing to rotate existing roles automatically: " + ", ".join(existing)
            )
        for role, privileges in ROLE_PRIVILEGES.items():
            _create_login_role(connection, role, passwords[role])
            _grant_privileges(connection, owner, database, role, privileges)
    return {
        role: connection_url_for_role(admin_url, role, password)
        for role, password in passwords.items()
    }


def write_secret_file(path: Path, urls: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    descriptor = os.open(path, flags, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as output:
        output.write("# Generated by db/provision_roles.py. Never commit this file.\n")
        output.write(f"DATABASE_READER_URL={urls['app_reader']}\n")
        output.write(f"DATABASE_WRITER_URL={urls['app_writer']}\n")
        output.write(f"DATABASE_ETL_URL={urls['etl_writer']}\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create Neon application roles and a local ignored secret file"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).parents[1] / ".env.neon",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="required acknowledgement that roles will be created",
    )
    args = parser.parse_args()
    if not args.apply:
        parser.error("--apply is required")
    if args.output.exists():
        parser.error(f"secret output already exists: {args.output}")

    urls = provision_roles(settings.database_url)
    write_secret_file(args.output, urls)
    print(f"Created roles: {', '.join(ROLE_PRIVILEGES)}")
    print(f"Saved connection URLs to ignored file: {args.output}")


if __name__ == "__main__":
    main()
