"""PostgreSQL initial schema with domain-native types."""

from alembic import op

revision = "0001_initial_postgresql"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE strategy (
            strategy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            strategy_key TEXT NOT NULL UNIQUE,
            strategy_name TEXT NOT NULL,
            description TEXT,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        INSERT INTO strategy (strategy_key, strategy_name, description)
        VALUES
            ('core', 'Core', '中核となる長期保有戦略'),
            ('satellite', 'Satellite', '成長機会を取り込む補完戦略'),
            ('alternatives', 'Alternatives', '伝統資産以外の分散戦略')
        ON CONFLICT (strategy_key) DO NOTHING;

        CREATE TABLE theme (
            theme_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            theme_key TEXT NOT NULL UNIQUE,
            theme_name TEXT NOT NULL,
            strategy_id BIGINT NOT NULL REFERENCES strategy(strategy_id),
            description TEXT,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE investment_target (
            target_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            target_key TEXT NOT NULL UNIQUE,
            target_name TEXT NOT NULL,
            target_type TEXT CHECK(target_type IN (
                'individual_stock','etf','mutual_fund','reit','bond','index','commodity'
            )),
            market TEXT,
            currency TEXT,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE data_source (
            source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_key TEXT NOT NULL UNIQUE,
            source_name TEXT NOT NULL,
            base_url TEXT,
            terms_url TEXT,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE ingestion_run (
            ingestion_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_type TEXT NOT NULL,
            git_commit_sha TEXT,
            source_id BIGINT NOT NULL REFERENCES data_source(source_id),
            status TEXT NOT NULL CHECK(status IN ('running','succeeded','partial','failed')),
            requested_from DATE,
            requested_to DATE,
            target_count INTEGER NOT NULL DEFAULT 0 CHECK(target_count >= 0),
            fetched_count INTEGER NOT NULL DEFAULT 0 CHECK(fetched_count >= 0),
            loaded_count INTEGER NOT NULL DEFAULT 0 CHECK(loaded_count >= 0),
            skipped_count INTEGER NOT NULL DEFAULT 0 CHECK(skipped_count >= 0),
            failed_count INTEGER NOT NULL DEFAULT 0 CHECK(failed_count >= 0),
            raw_path TEXT,
            error_message TEXT,
            started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            finished_at TIMESTAMPTZ
        );

        CREATE TABLE ingestion_error (
            error_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ingestion_run_id BIGINT NOT NULL REFERENCES ingestion_run(ingestion_run_id),
            entity_type TEXT,
            entity_key TEXT,
            stage TEXT NOT NULL,
            error_type TEXT,
            error_message TEXT NOT NULL,
            retryable BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE investment_target_identifier (
            investment_target_identifier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            target_id BIGINT NOT NULL REFERENCES investment_target(target_id),
            source_id BIGINT NOT NULL REFERENCES data_source(source_id),
            identifier_type TEXT NOT NULL,
            identifier TEXT NOT NULL,
            valid_from DATE NOT NULL DEFAULT DATE '0001-01-01',
            valid_to DATE,
            is_primary BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(source_id, identifier_type, identifier, valid_from),
            CHECK(valid_to IS NULL OR valid_to >= valid_from)
        );

        CREATE TABLE theme_investment_target (
            theme_id BIGINT NOT NULL REFERENCES theme(theme_id),
            target_id BIGINT NOT NULL REFERENCES investment_target(target_id),
            basket_weight DOUBLE PRECISION DEFAULT 1.0,
            rationale TEXT,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (theme_id, target_id)
        );

        CREATE TABLE market_price_observation (
            log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            target_id BIGINT NOT NULL REFERENCES investment_target(target_id),
            source_id BIGINT NOT NULL REFERENCES data_source(source_id),
            ingestion_run_id BIGINT REFERENCES ingestion_run(ingestion_run_id),
            obs_date DATE NOT NULL,
            open_price DOUBLE PRECISION,
            high_price DOUBLE PRECISION,
            low_price DOUBLE PRECISION,
            close_price DOUBLE PRECISION,
            volume DOUBLE PRECISION,
            price_basis TEXT NOT NULL DEFAULT 'unknown'
                CHECK(price_basis IN ('adjusted','unadjusted','unknown')),
            fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            note TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(target_id, source_id, obs_date)
        );

        CREATE TABLE financial_disclosure (
            disclosure_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            target_id BIGINT NOT NULL REFERENCES investment_target(target_id),
            source_id BIGINT NOT NULL REFERENCES data_source(source_id),
            disclosure_number TEXT NOT NULL,
            disclosed_date DATE NOT NULL,
            disclosed_time TIME,
            document_type TEXT NOT NULL,
            fiscal_period_type TEXT,
            period_start DATE,
            period_end DATE,
            fiscal_year_start DATE,
            fiscal_year_end DATE,
            accounting_standard TEXT,
            ingestion_run_id BIGINT REFERENCES ingestion_run(ingestion_run_id),
            source_record_hash TEXT,
            fetched_at TIMESTAMPTZ NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(source_id, disclosure_number),
            CHECK(period_end IS NULL OR period_start IS NULL OR period_end >= period_start),
            CHECK(fiscal_year_end IS NULL OR fiscal_year_start IS NULL OR fiscal_year_end >= fiscal_year_start)
        );

        CREATE TABLE financial_summary (
            disclosure_id BIGINT PRIMARY KEY REFERENCES financial_disclosure(disclosure_id) ON DELETE CASCADE,
            reporting_scope TEXT NOT NULL CHECK(reporting_scope IN ('consolidated','non_consolidated')),
            revenue BIGINT,
            operating_income BIGINT,
            ordinary_income BIGINT,
            net_income BIGINT,
            eps DOUBLE PRECISION,
            total_assets BIGINT,
            equity BIGINT,
            bps DOUBLE PRECISION,
            operating_cash_flow BIGINT,
            investing_cash_flow BIGINT,
            financing_cash_flow BIGINT,
            cash_equivalents BIGINT,
            forecast_revenue BIGINT,
            forecast_operating_income BIGINT,
            forecast_ordinary_income BIGINT,
            forecast_net_income BIGINT,
            forecast_eps DOUBLE PRECISION,
            next_forecast_revenue BIGINT,
            next_forecast_operating_income BIGINT,
            next_forecast_ordinary_income BIGINT,
            next_forecast_net_income BIGINT,
            next_forecast_eps DOUBLE PRECISION,
            annual_dividend_per_share DOUBLE PRECISION,
            forecast_annual_dividend_per_share DOUBLE PRECISION,
            shares_outstanding BIGINT,
            treasury_shares BIGINT,
            average_shares BIGINT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX idx_market_price_date ON market_price_observation(target_id, obs_date);
        CREATE INDEX idx_investment_target_identifier_target ON investment_target_identifier(target_id);
        CREATE INDEX idx_investment_target_identifier_lookup
            ON investment_target_identifier(source_id, identifier_type, identifier);
        CREATE INDEX idx_ingestion_run_status ON ingestion_run(status, started_at);
        CREATE INDEX idx_ingestion_error_run ON ingestion_error(ingestion_run_id);
        CREATE INDEX idx_financial_disclosure_target_date
            ON financial_disclosure(target_id, disclosed_date);
        CREATE INDEX idx_financial_disclosure_period
            ON financial_disclosure(target_id, fiscal_year_end, fiscal_period_type);
    """)


def downgrade() -> None:
    op.execute("""
        DROP TABLE IF EXISTS financial_summary;
        DROP TABLE IF EXISTS financial_disclosure;
        DROP TABLE IF EXISTS market_price_observation;
        DROP TABLE IF EXISTS theme_investment_target;
        DROP TABLE IF EXISTS investment_target_identifier;
        DROP TABLE IF EXISTS ingestion_error;
        DROP TABLE IF EXISTS ingestion_run;
        DROP TABLE IF EXISTS data_source;
        DROP TABLE IF EXISTS investment_target;
        DROP TABLE IF EXISTS theme;
        DROP TABLE IF EXISTS strategy;
    """)
